### ISSUE TITLE
Python 3.13 has no module named 'cgi', so I can't use biliarchiver.

### ISSUE THREAD

**Issue by gridkr** [saveweb/biliarchiver#14]
C:\Users\xxxxx\ .txxxxx\downloads>biliarchiver init
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python313\Scripts\biliarchiver.exe\__main__.py", line 4, in <module>
    from biliarchiver.cli_tools.biliarchiver import biliarchiver
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python313\Lib\site-packages\biliarchiver\cli_tools\biliarchiver.py", line 5, in <module>
    from biliarchiver.cli_tools.get_command import get
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python313\Lib\site-packages\biliarchiver\cli_tools\get_command.py", line 10, in <module>
    from bilix.sites.bilibili import api
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python313\Lib\site-packages\bilix\sites\bilibili\__init__.py", line 1, in <module>
    from .downloader import DownloaderBilibili
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python313\Lib\site-packages\bilix\sites\bilibili\downloader.py", line 10, in <module>
    from bilix.download.base_downloader_part import BaseDownloaderPart
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python313\Lib\site-packages\bilix\download\base_downloader_part.py", line 10, in <module>
    import cgi
ModuleNotFoundError: No module named 'cgi'

C:\Users\xxxxx\ .txxxxx\downloads>

**Comment by gridkr** [comment]
tubeup ([bibanon/tubeup]) is currently can archive BiliBili videos too, but they will not join the "BiliBili Videos" collection, and stuck in "Community Video" collection.

**Comment by OverflowCat** [comment]
Now you can [manually install](https://github.com/HFrost0/bilix/blob/master/CONTRIBUTING_EN.md) the latest version of bilix from its git repo, and the problem should be fixed.
