### ISSUE TITLE
[ERROR] error uploading BV_p1-ai-zh.srt to BiliBili-BV_p1-XXXXX, The specified bucket is not valid.

### ISSUE THREAD

**Issue by LaoshuBaby** [saveweb/biliarchiver#20]
```
 uploading BV1Nx4y1s76k_p1-ai-zh.srt: 100%|█████████████████████████████████████████████| 1/1 [00:01<00:00,  1.28s/MiB]
 error uploading BV1Nx4y1s76k_p1-ai-zh.srt: The specified bucket is not valid. - Bucket names should be valid archive identifiers; try someting matching this regular expression: ^[a-zA-Z0-9][a-zA-Z0-9_.-]{4,100}$ (or, if you are making unusual identifiers, this user may lack the special permission to do so)
上传 BV1Nx4y1s76k 时出错：
Traceback (most recent call last):
  File "C:\Environment\Python\Python311\Lib\site-packages\internetarchive\item.py", line 1106, in upload_file
    response.raise_for_status()
  File "C:\Environment\Python\Python311\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://s3.us.archive.org/BiliBili-BV1Nx4y1s76k_p1-8N1VB/BV1Nx4y1s76k_p1-ai-zh.srt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Environment\Python\Python311\Scripts\biliarchiver.exe\__main__.py", line 7, in <module>
  File "C:\Environment\Python\Python311\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Environment\Python\Python311\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Environment\Python\Python311\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Environment\Python\Python311\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Environment\Python\Python311\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Environment\Python\Python311\Lib\site-packages\biliarchiver\cli_tools\up_command.py", line 83, in up
    upload_bvid(
  File "C:\Environment\Python\Python311\Lib\site-packages\biliarchiver\_biliarchiver_upload_bvid.py", line 52, in upload_bvid
    raise e
  File "C:\Environment\Python\Python311\Lib\site-packages\biliarchiver\_biliarchiver_upload_bvid.py", line 38, in upload_bvid
    _upload_bvid(
  File "C:\Environment\Python\Python311\Lib\site-packages\biliarchiver\_biliarchiver_upload_bvid.py", line 235, in _upload_bvid
    r = item.upload(
        ^^^^^^^^^^^^
  File "C:\Environment\Python\Python311\Lib\site-packages\internetarchive\item.py", line 1277, in upload
    resp = self.upload_file(body,
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Environment\Python\Python311\Lib\site-packages\internetarchive\item.py", line 1131, in upload_file
    raise type(exc)(error_msg, response=exc.response, request=exc.request)
requests.exceptions.HTTPError:  error uploading BV1Nx4y1s76k_p1-ai-zh.srt to BiliBili-BV1Nx4y1s76k_p1-8N1VB, The specified bucket is not valid. - Bucket names should be valid archive identifiers; try someting matching this regular expression: ^[a-zA-Z0-9][a-zA-Z0-9_.-]{4,100}$ (or, if you are making unusual identifiers, this user may lack the special permission to do so)

```

**Comment by yzqzss** [comment]
你号没了。
